#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

# Check staged files with Lint-Staged
yarn test && yarn lint-staged

# increment package version based on commit message
if git log --format=%B -n 1 HEAD | grep -q 'bump major'; then
  yarn version --major --no-git-tag-version
elif git log --format=%B -n 1 HEAD | grep -q 'bump minor'; then
  yarn version --minor --no-git-tag-version
else
  yarn version --patch --no-git-tag-version
fi

# Commit the version bump & CHANGELOG
git add package.json
git add CHANGELOG.md
